module.exports = {
  graphql: require('./graphql'),
  jest: require('./jest'),
  prettierPlugin: require('./prettier-plugin'),
  prettierConfig: require('./prettier-config'),
  react: require('./react'),
  regexp: require('./regexp'),
  reactQuery: require('./react-query'),
  reactTestingLibrary: require('./rtl'),
  storybook: require('./storybook'),
  sonar: require('./sonar'),
  tailwind: require('./tailwind'),
  typescript: require('./typescript'),
  mdx: require('./mdx'),
  html: require('./html'),
}
