---
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master

name: 🦋 Create release or publish to pnpm

jobs:
  release:
    # Basic security: the release job can only be executed from this repo and from the master branch (not a remote thing)
    if: ${{ github.repository == 'wayofdev/npm-shareable-configs' && contains('refs/heads/master',github.ref)}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-22.04']
        node: ['18']

    steps:
      - name: 📦 Check out the codebase
        uses: actions/checkout@v3
        with:
          # To run comparison we need more than the latest commit.
          # @link https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
          fetch-depth: 0

      - name: ⚙️ Setup node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org/'

      - name: 📥 Monorepo install
        uses: wayofdev/gh-actions/actions/pnpm-install@master
        with:
          enable-corepack: true
          cache-node-modules: true

      # @link https://github.com/changesets/action
      - name: 🦋 Create Release pull request or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore: update versions'
          title: 'chore: update versions'
          cwd: ${{ github.workspace }}
          publish: pnpm run cs:publish
          version: pnpm run cs:version
          setupGitUser: true
          # Optional, might be used in conjunction with GITHUB_TOKEN to
          # allow running the workflows on a Version package action.
          # Be aware of security implications.
          # setupGitUser: true
        env:
          # See https://github.com/changesets/action/issues/147
          HOME: ${{ github.workspace }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
